repos:
  - repo: https://github.com/cmglezpdev/hulk-compiler
    # Ruff version.
    rev: v0.3.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format